name: Emprendimiento parcial config
type: module
description: Configuración para taller web desde cero. Creado por Mauricio Dinarte (@dinarcon). http://bit.ly/web-desde-cero
package: Migration
core: 8.x
hidden: 1
dependencies:
  - drupal:datetime
  - drupal:image
  - drupal:migrate
  - drupal:options
  - drupal:taxonomy
  - drupal:text
  - drupal:views
  - wdc_emprendimiento_parcial:wdc_emprendimiento_parcial_config
  - migrate_plus:migrate_plus
  - migrate_tools:migrate_tools
